module.exports = {
  HOME: 'Home',
  HOME_TITLE: 'Movie Center',
  HOME_DESCRIPTION: 'Find your movie by using our search form',
  POPULAR_MOVIES_TITLE: 'Popular Movies',
  POPULAR_MOVIES: '%{totalResults} Popular Movies',
  DETAIL_TITLE: 'Detail',
  SEARCH_RESULTS: '%{totalResults} Search Results for: %{query}',
  SEARCH_MOVIES: 'Search Movies',
  SEARCH_MOVIES_PLACEHOLDER: 'Type a Movie...',
  RESULTS_PAGINATION: 'Page %{page} of %{totalPages}',
  READ_ON: 'Read on',
  SIGNIN: 'Login',
  SIGNIN_PASSWORD_HINT: '123456',
  SIGNIN_PASSWORD_LABEL: 'password',
  SIGNIN_USER_HINT: 'user@server.com',
  SIGNIN_USER_LABEL: 'usuario',
  SIGNOUT: 'disconnect',
  SIGNUP: 'Create',
  SIGNUP_PASSWORD_LABEL: 'password',
  SIGNUP_USER: 'Create user',
  SIGNUP_USERNAME_LABEL: 'username',
  SIGNUP_USER_LABEL: 'mail',
  LOGIN_WITH_GOOGLE: 'Log in with your Google Account',
  LOGIN_WITH_FACEBOOK: 'Log in with your Facebook Account',
  FAVORITES_MOVIES_TITLE: 'My Favorite Movies',
  FAVORITE_MOVIES: '%{totalResults} Favorite movies'
}
