module.exports = {
  HOME: 'Inicio',
  HOME_TITLE: 'Central de Películas',
  HOME_DESCRIPTION:
    'Encuentra la información que buscas sobre tu película favorita a través de nuestro formulario de búsqueda o a través de las categorias',
  POPULAR_MOVIES_TITLE: 'Peliculas Populares',
  POPULAR_MOVIES: '%{totalResults} Peliculas Populares',
  DETAIL_TITLE: 'Detalle',
  SEARCH_RESULTS: '%{totalResults} resultados de la búsqueda para: %{query}',
  SEARCH_MOVIES: 'Buscar Peliculas',
  SEARCH_MOVIES_PLACEHOLDER: 'Escribe una peli...',
  RESULTS_PAGINATION: 'Página %{page} de %{totalPages}',
  READ_ON: 'Leer más',
  SIGNIN: 'Login',
  SIGNIN_PASSWORD_HINT: '123456',
  SIGNIN_PASSWORD_LABEL: 'contraseña',
  SIGNIN_USER_HINT: 'user@server.com',
  SIGNIN_USER_LABEL: 'user',
  SIGNOUT: 'desconectar',
  SIGNUP: 'Crear',
  SIGNUP_PASSWORD_LABEL: 'contraseña',
  SIGNUP_USER: 'Crear usuario',
  SIGNUP_USERNAME_LABEL: 'nombre de usuario',
  SIGNUP_USER_LABEL: 'correo electrónico',
  LOGIN_WITH_GOOGLE: 'Entra con tu cuenta de Google',
  LOGIN_WITH_FACEBOOK: 'Entra con tu cuenta de Facebook',
  FAVORITES_MOVIES_TITLE: 'Mis Peliculas Favoritas',
  FAVORITE_MOVIES: '%{totalResults} Peliculas favoritas'
}
