sudo: required

language: node_js

node_js:
    - '8'


cache:
  directories:
  - node_modules

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - npm install -g surge
  - npm install --prefer-online

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run ssr:deploy:pr; fi'

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run ssr:deploy:production
    on:
      branch: master
